### ISSUE TITLE
Unreachable code in kiva.font_manager.is_string_like

### ISSUE THREAD

**Issue by pbrod** [enthought/enable#394]
The lines
https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/fonttools/font_manager.py#L221-L225
are unreachable due to an indentation bug since they  most likely should be reachable.

The if statement 
https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/fonttools/font_manager.py#L217-L220

can be simplified.  The if statement can be replaced with 
```pyhton
return bool(obj.ndim == 0 and obj.dtype.kind in 'SU')
```

**Comment by jwiggins** [comment]
Wow... Did some code spelunking on this one.

Here's how the code _should_ look:
https://github.com/matplotlib/matplotlib/blob/87885e754970138b2a9de717ed4ff1c211defefd/lib/matplotlib/cbook/__init__.py#L496-L510

However, [this happened](https://github.com/enthought/enable/commit/1fe9c35c1f28e8b8e23c8a3614dc04e606227dc5#diff-c5d5697b628a1276a08c8018c5ed0484b61b328a2b6ede6ffadadf0bd673d728R201-R212) in 1fe9c35c1f28e8b8e23c8a3614dc04e606227dc5.

But since this code was taken from matplotlib anyways, perhaps we should emulate matplotlib/matplotlib#7996?

**Comment by rahulporuri** [comment]
> But since this code was taken from matplotlib anyways, perhaps we should emulate matplotlib/matplotlib#7996?

Yep. That sounds like a better idea. We can even get rid of `six.string_types`!
