### ISSUE TITLE
ContextMenuTool not advertised in any api module

### ISSUE THREAD

**Issue by notmatthancock** [enthought/enable#441]
This is a useful tool, but not easily discoverable. Perhaps it can go in `enable.tools.api`?

**Comment by kitchoi** [comment]
While we are at this, it might be worth moving the content of the module out of the `enable.tools.pyface` namespace (which contains only one thing)? We can keep the imports as aliases for backward compatibility.

Looking into the pull request that added the tool (https://github.com/enthought/enable/pull/84), looks like the original intent was to keep `pyface` an optional dependency. But I think the package has changed since and `enable.tools.api` probably already requires `pyface` one way or another (e.g. `hover_tool` imports `pyface`).

**Comment by kitchoi** [comment]
I think I should open a separate issue for the subpackage, it is orthogonal to exposing the tool via the api module. Sorry for noise.

**Comment by corranwebster** [comment]
Yes, this was written when Enaml was more of a thing and it was annoying to have Pyface as a dependency when writing Enaml apps, so we were working to remove it.  There's also some gorpiness around the Pyglet/OpenGL and VTK/TVTK backends because we don't have a Pyglet or TVTK backend for Pyface.

We have to be a bit careful - I think it is OK for us to have the Wx or Qt backends depending on Pyface as a matter pr practicality, but making this part of the public API may break the Pyglet backend, for example.
