### ISSUE TITLE
Graphics context size doubled on macOS

### ISSUE THREAD

**Issue by oeyh** [enthought/enable#742]
Here is an example to reproduce it:

```python
from enable.api import Component, ComponentEditor
from traits.api import HasTraits, Instance
from traitsui.api import UItem, View


class PatchedComponent(Component):
    def draw(self, gc, **kwargs):
        print("gc width", gc.width())
        print("gc height", gc.height())
        super().draw(gc, **kwargs)


class TestPlot(HasTraits):
    canvas = Instance(PatchedComponent)

    def _canvas_default(self):
        return PatchedComponent()

    def default_traits_view(self):
        return View(
            UItem(
                'canvas',
                editor=ComponentEditor()
            ),
            width=300,
            height=200,
        )


if __name__ == '__main__':

    TestPlot().configure_traits()
```

When running it on Windows or Linux, it prints `gc width=301 and height=201`; but on macOS, it prints `width=601 and height=401` instead. The canvas size is doubled. 

We are on Enable 5.0.1 and use pyqt5 backend.

We noticed it because in our project we patched the `draw()` method and used gc width and height to define new view bounds.

**Comment by jwiggins** [comment]
This is expected. On macOS, you have a high resolution display and Qt is taking advantage of it. Enable now detects this and creates a graphics context with the appropriate size. Note that your components are still sized in "logical" coordinates (rather than "device" coordinates).

To work with high resolution displays you have two options:
* Change your code to use the bounds of the `Component` instance and not the pixel size of the `GraphicsContext` which is created on its behalf.
* Pass `high_resolution=False` to your `ComponentEditor` to disable high resolution rendering.

**Comment by notmatthancock** [comment]
> This is expected.

By whom? :grinning: 

> Change your code to use the bounds of the Component instance and not the pixel size of the GraphicsContext which is created on its behalf.

Ah, so we have a chicken and egg problem with this. We're using `gc.width()` and `gc.height()` to reset the component position and bounds on draws, so that a chaco plot fills always fills out the plot area. If I recall correctly, we introduced this hack because switching between images with different aspect ratios caused the plot area to shrink away to 0. 

I'm looking at the code in https://github.com/enthought/enable/pull/591/files, and if I understand correctly, I think a straightforward solution for us would be to replace `gc.width()` in our code with `gc.width() / self.window.base_pixel_scale`.

**Comment by jwiggins** [comment]
> We're using `gc.width()` and `gc.height()` to reset the component position and bounds on draws

This sounds like the wrong solution, but I need to better understand the problem being solved.

**Comment by corranwebster** [comment]
I think I found the code in question, and I don't think it is doing something sensible, which makes me wonder what problem it was _actually_ solving. @oeyh can you please reach out to me with more context.

**Comment by jwiggins** [comment]
Yes, the project's workaround for #747 is causing trouble now that the size of a GC is different when using HiDPI.
